// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: EnumCmdID.proto

#include "EnumCmdID.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
namespace pb {
}  // namespace pb
static constexpr ::PROTOBUF_NAMESPACE_ID::Metadata* file_level_metadata_EnumCmdID_2eproto = nullptr;
static const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* file_level_enum_descriptors_EnumCmdID_2eproto[1];
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_EnumCmdID_2eproto = nullptr;
const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_EnumCmdID_2eproto::offsets[1] = {};
static constexpr ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema* schemas = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::Message* const* file_default_instances = nullptr;

const char descriptor_table_protodef_EnumCmdID_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\017EnumCmdID.proto\022\002pb*Z\n\tMessageID\022\013\n\007UN"
  "KNOWN\020\000\022\t\n\004PING\020\350\007\022\n\n\005SCENE\020\351\007\022\n\n\005LOGIN\020"
  "\352\007\022\013\n\006RECORD\020\353\007\022\020\n\013GAME_RECORD\020\354\007B\007Z\005./;"
  "pbb\006proto3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_EnumCmdID_2eproto_deps[1] = {
};
static ::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase*const descriptor_table_EnumCmdID_2eproto_sccs[1] = {
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_EnumCmdID_2eproto_once;
static bool descriptor_table_EnumCmdID_2eproto_initialized = false;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_EnumCmdID_2eproto = {
  &descriptor_table_EnumCmdID_2eproto_initialized, descriptor_table_protodef_EnumCmdID_2eproto, "EnumCmdID.proto", 130,
  &descriptor_table_EnumCmdID_2eproto_once, descriptor_table_EnumCmdID_2eproto_sccs, descriptor_table_EnumCmdID_2eproto_deps, 0, 0,
  schemas, file_default_instances, TableStruct_EnumCmdID_2eproto::offsets,
  file_level_metadata_EnumCmdID_2eproto, 0, file_level_enum_descriptors_EnumCmdID_2eproto, file_level_service_descriptors_EnumCmdID_2eproto,
};

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_EnumCmdID_2eproto = (  ::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_EnumCmdID_2eproto), true);
namespace pb {
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* MessageID_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_EnumCmdID_2eproto);
  return file_level_enum_descriptors_EnumCmdID_2eproto[0];
}
bool MessageID_IsValid(int value) {
  switch (value) {
    case 0:
    case 1000:
    case 1001:
    case 1002:
    case 1003:
    case 1004:
      return true;
    default:
      return false;
  }
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace pb
PROTOBUF_NAMESPACE_OPEN
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
